# Generated by Django 3.0.3 on 2020-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date.')),
                ('title', models.CharField(default='', help_text='Title.', max_length=400)),
                ('subtitle', models.CharField(default='', help_text='Subtitle.', max_length=10000)),
                ('summary', models.TextField(default='', help_text='Summary.', max_length=10000)),
                ('first_paragraph', models.TextField(default='', help_text='First paragraph.')),
                ('last_paragraphs', models.TextField(default='', help_text='Last paragraphs.')),
                ('main_picture', models.CharField(default='', help_text='Main picture.', max_length=400)),
                ('url_name', models.CharField(default='', help_text='Name that display in the url.', max_length=400)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Month and year of the news item.')),
                ('text', models.CharField(help_text='News item.', max_length=400)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Year of the publication.')),
                ('name', models.CharField(default='', help_text='Name of the publication.', max_length=400)),
                ('authors', models.CharField(default='', help_text='Authors of the publication.', max_length=400)),
                ('arxiv_link', models.CharField(default='', help_text='ArXiV link.', max_length=400)),
                ('code_link', models.CharField(default='', help_text='Code link.', max_length=400)),
                ('venue_name', models.CharField(default='', help_text='Venue name.', max_length=400)),
                ('venue_link', models.CharField(default='', help_text='Venue link.', max_length=400)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Month and year of the talk.')),
                ('location', models.CharField(default='Unknown location', help_text='Location.', max_length=400)),
                ('event_name', models.CharField(default='', help_text='Name of the event.', max_length=400)),
                ('event_link', models.CharField(default='', help_text='Event link.', max_length=400)),
                ('poster_filename', models.CharField(default='', help_text='Poster file name.', max_length=400)),
                ('slides_filename', models.CharField(default='', help_text='Slides handout file name.', max_length=400)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
